version: '3.4'
volumes:
  db-data:
    driver: local

services:
  api:
    container_name: api
    build:
      context: .
      args:
        RUN_ENVIRONMENT: development
    environment:
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/app
    working_dir: /app/src
    links:
      - db
    depends_on:
      - db


  db:
    image: postgres:11.0
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: teste
      POSTGRES_USER: teste
      POSTGRES_DB: hummingbird-v2
    volumes:
      - db-data:/var/lib/postgresql/data
      - .:/app
    ports:
      - 5432:5432





