version: '3.4'

services:

  db:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_PASSWORD: teste
      POSTGRES_USER: teste
      POSTGRES_DB: hummingbird-v2
    ports:
      - "54320:5432"
    expose:
      - "5432"

  web:
    build:
      context: .
      args:
        RUN_ENVIRONMENT: development
    environment:
      FLASK_DEBUG: 1
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: '/app/src'
