# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        echo $PYTHONPATH
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install -r requirements_local.txt
        echo $PYTHONPATH
      env:
        FLASK_APP: main.py
        FLASK_ENV: testing
    - name: Test with unittest
      run: |
        echo $PYTHONPATH
        python tests/runner.py
